export const PREFIX = `TRADE_`;
export const EXAMPLE_LIST = `EXAMPLE_LIST`;

export const TRADE_REQUEST_FETCH_LIST = `${PREFIX}REQUEST_FETCH_LIST`;
export const TRADE_RECEIVE_FETCH_LIST = `${PREFIX}RECEIVE_FETCH_LIST`;

export const TRADE_REQUEST_CREATE = `${PREFIX}REQUEST_CREATE`;

export const TRADE_REQUEST_DELETE = `${PREFIX}REQUEST_DELETE`;
